export const typesOrder = {
  CREATE_ORDER_START: "CREATE_ORDER_START",
  CREATE_ORDER_SUCCESS: "CREATE_ORDER_SUCCESS",
  CREATE_ORDER_ERROR: "CREATE_ORDER_ERROR",
  MY_ORDERS_START: "MY_ORDERS_START",
  MY_ORDERS_SUCCESS: "MY_ORDERS_SUCCESS",
  MY_ORDERS_ERROR: "MY_ORDERS_ERROR",
  ORDER_DETAILS_START: "ORDER_DETAILS_START",
  ORDER_DETAILS_SUCCESS: "ORDER_DETAILS_SUCCESS",
  ORDER_DETAILS_ERROR: "ORDER_DETAILS_ERROR",
  ORDER_CLEAR_ERROR: "ORDER_CLEAR_ERROR",
};
