export const typesAuth = {
  LOGIN_START: "LOGIN_START",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_ERROR: "LOGIN_ERROR",

  REGISTER_START: "REGISTER_START",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_ERROR: "REGISTER_ERROR",

  ACCESS_REFRESH_START: "ACCESS_REFRESH_START",
  ACCESS_REFRESH_SUCCESS: "ACCESS_REFRESH_SUCCESS",
  ACCESS_REFRESH_ERROR: "ACCESS_REFRESH_ERROR",

  LS_AND_SS_CREDENTIALS: "LS_AND_SS_CREDENTIALS",

  LOGOUT: "LOGOUT",

  AUTH_CLEAR_ERROR: "AUTH_CLEAR_ERROR",
};
