export const typesUser = {
  USER_CLEAR_ERROR: "USER_CLEAR_ERROR",

  UPDATE_PROFILE_START: "UPDATE_PROFILE_START",
  UPDATE_PROFILE_SUCCESS: "UPDATE_PROFILE_SUCCESS",
  UPDATE_PROFILE_ERROR: "UPDATE_PROFILE_ERROR",
  UPDATE_PROFILE_RESET: "UPDATE_PROFILE_RESET",

  GET_USER_DETAILS_START: "GET_USER_DETAILS_START",
  GET_USER_DETAILS_SUCCESS: "GET_USER_DETAILS_SUCCESS",
  GET_USER_DETAILS_ERROR: "GET_USER_DETAILS_ERROR",
  GET_USER_DETAILS_CLEAR_ERROR: "GET_USER_DETAILS_CLEAR_ERROR",

  UPDATE_PASSWORD_START: "UPDATE_PASSWORD_START",
  UPDATE_PASSWORD_SUCCESS: "UPDATE_PASSWORD_SUCCESS",
  UPDATE_PASSWORD_ERROR: "UPDATE_PASSWORD_ERROR",
  UPDATE_PASSWORD_RESET: "UPDATE_PASSWORD_RESET",

  FORGOT_PASSWORD_START: "FORGOT_PASSWORD_START",
  FORGOT_PASSWORD_SUCCESS: "FORGOT_PASSWORD_SUCCESS",
  FORGOT_PASSWORD_ERROR: "FORGOT_PASSWORD_ERROR",

  NEW_PASSWORD_START: "NEW_PASSWORD_START",
  NEW_PASSWORD_SUCCESS: "NEW_PASSWORD_SUCCESS",
  NEW_PASSWORD_ERROR: "NEW_PASSWORD_ERROR",
};
